---
- name: "3.3.1 | Ensure IP forwarding is disabled"
  block:
    - name: "3.3.1 | Ensure IP forwarding is disabled | IPv4 settings"
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "0"
        sysctl_set: true
        sysctl_file: "{{ cis_sysctl_network_conf }}"
        state: present
        reload: true
        ignoreerrors: true
      notify:
        - Flush ipv4 route table

    - name: "3.3.1 | Ensure IP forwarding is disabled | IPv6 settings"
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: "0"
        sysctl_set: true
        sysctl_file: "{{ cis_sysctl_network_conf }}"
        state: present
        reload: true
        ignoreerrors: true
      when: cis_ipv6_disable == 'sysctl'
      notify:
        - Flush ipv6 route table
  when:
    - not cis_is_router
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 3.3.1
    - ip_forwarding
    - sysctl

- name: "3.3.2 | Ensure packet redirect sending is disabled"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "0"
    sysctl_set: true
    sysctl_file: "{{ cis_sysctl_network_conf }}"
    state: present
    reload: true
    ignoreerrors: true
  with_items:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
  notify: Flush ipv4 route table
  when:
    - not cis_is_router
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 3.3.2
    - packet_redirect
    - sysctl

- name: "3.3.3 | Ensure bogus ICMP responses are ignored"
  ansible.posix.sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: "1"
    sysctl_set: true
    sysctl_file: "{{ cis_sysctl_network_conf }}"
    state: present
    reload: true
    ignoreerrors: true
  notify: Flush ipv4 route table
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 3.3.3
    - icmp
    - sysctl

- name: "3.3.4 | Ensure broadcast ICMP requests are ignored"
  ansible.posix.sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: "1"
    sysctl_set: true
    sysctl_file: "{{ cis_sysctl_network_conf }}"
    state: present
    reload: true
    ignoreerrors: true
  notify: Flush ipv4 route table
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 3.3.4
    - icmp
    - sysctl

- name: "3.3.5 | Ensure icmp redirects are not accepted"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "0"
    sysctl_set: true
    sysctl_file: "{{ cis_sysctl_network_conf }}"
    state: present
    reload: true
    ignoreerrors: true
  with_items:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
  notify: Flush ipv4 route table
  when:
    - not cis_is_router
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 3.3.5
    - packet_redirect
    - sysctl

- name: "3.3.6 | Ensure secure icmp redirects are not accepted"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "0"
    sysctl_set: true
    sysctl_file: "{{ cis_sysctl_network_conf }}"
    state: present
    reload: true
    ignoreerrors: true
  with_items:
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects
  notify: Flush ipv4 route table
  when:
    - not cis_is_router
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 3.3.6
    - packet_redirect
    - sysctl

- name: "3.3.7 | Ensure Reverse Path Filtering is enabled"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: true
    sysctl_file: "{{ cis_sysctl_network_conf }}"
    state: present
    reload: true
    ignoreerrors: true
  with_items:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter
  notify: Flush ipv4 route table
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 3.3.7
    - reverse_path_filtering
    - sysctl

- name: "3.3.8 | Ensure source routed packets are not accepted"
  block:
    - name: "3.3.8 | Ensure source routed packets are not accepted | IPv4 settings"
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "0"
        sysctl_set: true
        sysctl_file: "{{ cis_sysctl_network_conf }}"
        state: present
        reload: true
        ignoreerrors: true
      with_items:
        - net.ipv4.conf.all.accept_source_route
        - net.ipv4.conf.default.accept_source_route
      notify: Flush ipv4 route table

    - name: "3.3.8 | Ensure source routed packets are not accepted | IPv6 settings"
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "0"
        sysctl_set: true
        sysctl_file: "{{ cis_sysctl_network_conf }}"
        state: present
        reload: true
        ignoreerrors: true
      when: cis_ipv6_disable == 'sysctl'
      with_items:
        - net.ipv6.conf.all.accept_source_route
        - net.ipv6.conf.default.accept_source_route
      notify: Flush ipv6 route table
  when:
    - not cis_is_router
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 3.3.8
    - routed_packets
    - sysctl

- name: "3.3.9 | Ensure suspicious packets are logged"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: true
    sysctl_file: "{{ cis_sysctl_network_conf }}"
    state: present
    reload: true
    ignoreerrors: true
  with_items:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians
  notify: Flush ipv4 route table
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 3.3.9
    - suspicious_packets
    - sysctl

- name: "3.3.10 | Ensure TCP SYN Cookies is enabled"
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: "1"
    sysctl_set: true
    sysctl_file: "{{ cis_sysctl_network_conf }}"
    state: present
    reload: true
    ignoreerrors: true
  notify: Flush ipv4 route table
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 3.3.10
    - tcp_syn_cookies
    - sysctl

- name: "3.3.11 | Ensure IPv6 router advertisements are not accepted"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "0"
    sysctl_set: true
    sysctl_file: "{{ cis_sysctl_network_conf }}"
    state: present
    reload: true
    ignoreerrors: true
  with_items:
    - net.ipv6.conf.all.accept_ra
    - net.ipv6.conf.default.accept_ra
  notify: Flush ipv6 route table
  when:
    - cis_ipv6_required
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 3.3.11
    - ipv6
    - router_advertisements
    - sysctl
