---
- name: "2.3.1.1 | Ensure a single time synchronization daemon is in use"
  block:
    - name: "2.3.1.1 | Ensure a single time synchronization daemon is in use | Pkg installed"
      package:
        name: "{{ cis_time_sync_tool }}"
        state: present

    - name: "2.3.1.1 | Ensure a single time synchronization daemon is in use | other pkgs removed"
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - chrony
        - ntp
      when: item != cis_time_sync_tool

    - name: "2.3.1.1 | Ensure a single time synchronization daemon is in use | mask service"
      service:
        name: systemd-timesyncd
        state: stopped
        enabled: false
        masked: true
        daemon_reload: true
      when:
        - cis_time_sync_tool != "systemd-timesyncd"
        - "'systemd-timesyncd' in ansible_facts.packages"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 2.3.1.1
    - chrony
    - ntp
    - systemd-timesyncd

- name: "2.3.2.1 | Ensure systemd-timesyncd configured with authorized timeserver"
  block:
    - name: "2.3.2.1 | Ensure systemd-timesyncd configured with authorized timeserver | create conf.d dir"
      file:
        path: /etc/systemd/timesyncd.conf.d
        owner: root
        group: root
        mode: "0755"
        state: directory

    - name: "2.3.2.1 | Ensure systemd-timesyncd configured with authorized timeserver | sources"
      template:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
        mode: "0644"
        owner: root
        group: root
      loop:
        - "etc/systemd/timesyncd.conf.d/50-timesyncd.conf"
      notify: Restart timeservice
  when:
    - cis_time_sync_tool == "systemd-timesyncd"
  tags:
    - level1-server
    - level1-workstation
    - patch
    - 2.3.2.1
    - timesyncd

- name: "2.3.2.2 | Ensure systemd-timesyncd is enabled and running"
  block:
    - name: "2.3.2.2 | Ensure systemd-timesyncd is enabled and running | Ensure package is installed"
      apt:
        name: systemd-timesyncd
        state: present

    - name: "2.3.2.2 | Ensure systemd-timesyncd is enabled and running | Start service"
      systemd:
        name: systemd-timesyncd
        state: started
        enabled: true
        masked: false
  when:
    - cis_time_sync_tool == "systemd-timesyncd"
  tags:
    - level1-server
    - level1-workstation
    - 2.3.2.2
    - timesyncd

- name: "2.3.3.1 | Ensure chrony is configured with authorized timeserver"
  block:
    - name: "2.3.3.1 | Ensure chrony is configured with authorized timeserver | Ensure /etc/chrony directory exists"
      file:
        path: /etc/chrony
        state: directory
        mode: "0644"
        owner: root
        group: root

    - name: "2.3.3.1 | Ensure chrony is configured with authorized timeserver | sources"
      template:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
        mode: "0644"
        owner: root
        group: root
      loop:
        - etc/chrony/sources.d/pool.sources
        - etc/chrony/sources.d/server.sources
      notify: Restart timeservice

    - name: "2.3.3.1 | Ensure chrony is configured with authorized timeserver | load sources"
      lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: "^sourcedir /etc/chrony/sources.d"
        line: sourcedir /etc/chrony/sources.d
      notify: Restart timeservice
  when:
    - cis_time_sync_tool == "chrony"
  tags:
    - level1-server
    - level1-workstation
    - patch
    - 2.3.3.1
    - chrony

- name: "2.3.3.2 | Ensure chrony is running as user _chrony"
  lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: "^user _chrony"
    line: "user _chrony"
  when:
    - cis_time_sync_tool == "chrony"
  tags:
    - level1-server
    - level1-workstation
    - patch
    - 2.3.3.2
    - chrony

- name: "2.3.3.3 | Ensure chrony is enabled and running"
  systemd:
    name: chrony
    state: started
    enabled: true
  when:
    - cis_time_sync_tool == "chrony"
  tags:
    - level1-server
    - level1-workstation
    - 2.3.3.3
    - chrony
