---
- name: "1.1.1.1 | Ensure cramfs kernel module is not available"
  block:
    - name: "1.1.1.1 | Ensure cramfs kernel module is not available | Edit modprobe config"
      lineinfile:
        dest: /etc/modprobe.d/cramfs.conf
        regexp: '^(#)?install cramfs(\\s|$)'
        line: install cramfs /bin/true
        create: true

    - name: "1.1.1.1 | Ensure cramfs kernel module is not available | blacklist"
      lineinfile:
        path: /etc/modprobe.d/blacklist.conf
        regexp: "^(#)?blacklist cramfs(\\s|$)"
        line: "blacklist cramfs"
        create: true
        mode: "0600"

    - name: "1.1.1.1 | Ensure cramfs kernel module is not available | Disable cramfs"
      community.general.modprobe:
        name: cramfs
        state: absent
  notify: Update_Initramfs
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.1.1.1
    - cramfs

- name: "1.1.1.2 | Ensure freevxfs kernel module is not available"
  block:
    - name: "1.1.1.2 | Ensure freevxfs kernel module is not available | Edit modprobe config"
      lineinfile:
        dest: /etc/modprobe.d/freevxfs.conf
        regexp: '^(#)?install freevxfs(\\s|$)'
        line: install freevxfs /bin/true
        create: true

    - name: "1.1.1.2 | Ensure freevxfs kernel module is not available | blacklist"
      lineinfile:
        path: /etc/modprobe.d/blacklist.conf
        regexp: "^(#)?blacklist freevxfs(\\s|$)"
        line: "blacklist freevxfs"
        create: true
        mode: "0600"

    - name: "1.1.1.2 | Ensure freevxfs kernel module is not available | Disable freevxfs"
      community.general.modprobe:
        name: freevxfs
        state: absent
  notify: Update_Initramfs
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.1.1.2
    - freevxfs

- name: "1.1.1.3 | Ensure hfs kernel module is not available"
  block:
    - name: "1.1.1.3 | Ensure hfs kernel module is not available | Edit modprobe config"
      lineinfile:
        dest: /etc/modprobe.d/hfs.conf
        regexp: '^(#)?install hfs(\\s|$)'
        line: install hfs /bin/true
        create: true

    - name: "1.1.1.3 | Ensure hfs kernel module is not available | blacklist"
      lineinfile:
        path: /etc/modprobe.d/blacklist.conf
        regexp: "^(#)?blacklist hfs(\\s|$)"
        line: "blacklist hfs"
        create: true
        mode: "0600"

    - name: "1.1.1.3 | Ensure hfs kernel module is not available | Disable hfs"
      community.general.modprobe:
        name: hfs
        state: absent
  notify: Update_Initramfs
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.1.1.3
    - hfs

- name: "1.1.1.4 | Ensure hfsplus kernel module is not available"
  block:
    - name: "1.1.1.4 | Ensure hfsplus kernel module is not available | Edit modprobe config"
      lineinfile:
        dest: /etc/modprobe.d/hfsplus.conf
        regexp: '^(#)?install hfsplus(\\s|$)'
        line: install hfsplus /bin/true
        create: true

    - name: "1.1.1.4 | Ensure hfsplus kernel module is not available | blacklist"
      lineinfile:
        path: /etc/modprobe.d/blacklist.conf
        regexp: "^(#)?blacklist hfsplus(\\s|$)"
        line: "blacklist hfsplus"
        create: true
        mode: "0600"

    - name: "1.1.1.4 | Ensure hfsplus kernel module is not available | Disable hfsplus"
      community.general.modprobe:
        name: hfsplus
        state: absent
  notify: Update_Initramfs
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.1.1.4
    - hfsplus

- name: "1.1.1.5 | Ensure jffs2 kernel module is not available"
  block:
    - name: "1.1.1.5 | Ensure jffs2 kernel module is not available | Edit modprobe config"
      lineinfile:
        dest: /etc/modprobe.d/jffs2.conf
        regexp: '^(#)?install jffs2(\\s|$)'
        line: install jffs2 /bin/true
        create: true

    - name: "1.1.1.5 | Ensure jffs2 kernel module is not available | blacklist"
      lineinfile:
        path: /etc/modprobe.d/blacklist.conf
        regexp: "^(#)?blacklist jffs2(\\s|$)"
        line: "blacklist jffs2"
        create: true
        mode: "0600"

    - name: "1.1.1.5 | Ensure jffs2 kernel module is not available | Disable jffs2"
      community.general.modprobe:
        name: jffs2
        state: absent
  notify: Update_Initramfs
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.1.1.5
    - jffs2

- name: "1.1.1.6 | Ensure squashfs kernel module is not available"
  block:
    - name: "1.1.1.6 | Ensure squashfs kernel module is not available | Edit modprobe config"
      lineinfile:
        dest: /etc/modprobe.d/squashfs.conf
        regexp: '^(#)?install squashfs(\\s|$)'
        line: install squashfs /bin/true
        create: true

    - name: "1.1.1.6 | Ensure squashfs kernel module is not available | blacklist"
      lineinfile:
        path: /etc/modprobe.d/blacklist.conf
        regexp: "^(#)?blacklist squashfs(\\s|$)"
        line: "blacklist squashfs"
        create: true
        mode: "0600"

    - name: "1.1.1.6 | Ensure squashfs kernel module is not available | Disable squashfs"
      community.general.modprobe:
        name: squashfs
        state: absent
  notify: Update_Initramfs
  when:
    - snap_pkg_mgr.stdout == "0"
    - squashfs_builtin.stdout == "0"
  tags:
    - level2-server
    - level2-workstation
    - automated
    - patch
    - 1.1.1.6
    - squashfs

- name: "1.1.1.7 | Ensure udf kernel module is not available"
  block:
    - name: "1.1.1.7 | Ensure udf kernel module is not available | Edit modprobe config"
      lineinfile:
        dest: /etc/modprobe.d/udf.conf
        regexp: '^(#)?install udf(\\s|$)'
        line: install udf /bin/true
        create: true

    - name: "1.1.1.7 | Ensure udf kernel module is not available | blacklist"
      lineinfile:
        path: /etc/modprobe.d/blacklist.conf
        regexp: "^(#)?blacklist udf(\\s|$)"
        line: "blacklist udf"
        create: true
        mode: "0600"

    - name: "1.1.1.7 | Ensure udf kernel module is not available | Disable udf"
      community.general.modprobe:
        name: udf
        state: absent
  notify: Update_Initramfs
  tags:
    - level2-server
    - level2-workstation
    - automated
    - patch
    - 1.1.1.7
    - udf

- name: "1.1.1.8 | Ensure usb-storage kernel module is not available"
  block:
    - name: "1.1.1.8 | Ensure usb-storage kernel module is not available | Edit modprobe config"
      lineinfile:
        dest: /etc/modprobe.d/usb-storage.conf
        regexp: '^(#)?install usb-storage(\\s|$)'
        line: install usb-storage /bin/true
        create: true

    - name: "1.1.1.8 | Ensure usb-storage kernel module is not available | blacklist"
      lineinfile:
        path: /etc/modprobe.d/blacklist.conf
        regexp: "^(#)?blacklist usb-storage(\\s|$)"
        line: "blacklist usb-storage"
        create: true
        mode: "0600"

    - name: "1.1.1.8 | Ensure usb-storage kernel module is not available | Disable usb-storage"
      community.general.modprobe:
        name: usb-storage
        state: absent
  notify: Update_Initramfs
  tags:
    - level2-server
    - level2-workstation
    - automated
    - patch
    - 1.1.1.8
    - usb-storage
