---
- name: "1.7.1 | Ensure GNOME Display Manager is removed"
  package:
    name: gdm3
    state: absent
  when:
    - not cis_desktop_required
    - cis_disruption_high
    - "'gdm3' in ansible_facts.packages"
  tags:
    - level2-server
    - manual
    - patch
    - 1.7.1
    - gnome

- name: "1.7.2 | Ensure GDM login banner is configured"
  block:
    - name: "1.7.2 | Ensure GDM login banner is configured | Make directory"
      file:
        path: "/etc/dconf/db/{{ cis_dconf_db_name }}.d"
        owner: root
        group: root
        mode: "0755"
        state: directory

    - name: "1.7.2 | Ensure GDM login banner is configured | Banner settings"
      lineinfile:
        path: "/etc/dconf/db/{{ cis_dconf_db_name }}.d/00-login-screen"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.insertafter }}"
        create: true
        owner: root
        group: root
        mode: "0644"
      loop:
        - {
            regexp: '\[org\/gnome\/login-screen\]',
            line: "[org/gnome/login-screen]",
            insertafter: EOF,
          }
        - {
            regexp: "banner-message-enable",
            line: "banner-message-enable=true",
            insertafter: '\[org\/gnome\/login-screen\]',
          }
        - {
            regexp: "banner-message-text",
            line: "banner-message-text='{{ cis_warning_banner | regex_replace('\n', ' ') | trim }}'",
            insertafter: "banner-message-enable",
          }
  notify: Update dconf
  when:
    - cis_desktop_required
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.7.2
    - gnome

- name: "1.7.3 | Ensure disable-user-list is enabled"
  block:
    - name: "1.7.3 | Ensure disable-user-list is enabled | Make directories"
      file:
        path: "{{ item }}"
        owner: root
        group: root
        mode: "0755"
        state: directory
      loop:
        - /etc/dconf/db/{{ cis_dconf_db_name }}.d
        - /etc/dconf/profile

    - name: "1.7.3 | Ensure disable-user-list is enabled | Disable-user-list setting login-screen"
      lineinfile:
        path: "/etc/dconf/db/{{ cis_dconf_db_name }}.d/00-login-screen"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.insertafter }}"
        create: true
        owner: root
        group: root
        mode: "0644"
      loop:
        - {
            regexp: '\[org\/gnome\/login-screen\]',
            line: "[org/gnome/login-screen]",
            insertafter: EOF,
          }
        - {
            regexp: "disable-user-list",
            line: "disable-user-list=true",
            insertafter: '\[org\/gnome\/login-screen\]',
          }

    - name: "1.7.3 | Ensure disable-user-list is enabled | Disable-user-list setting profile"
      lineinfile:
        path: "/etc/dconf/profile/{{ cis_dconf_db_name }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.insertafter }}"
        create: true
        owner: root
        group: root
        mode: "0644"
      loop:
        - { regexp: "^user-db:user", line: "user-db:user", insertafter: EOF }
        - {
            regexp: "^system-db:{{ cis_dconf_db_name }}",
            line: "system-db:{{ cis_dconf_db_name }}",
            insertafter: "user-db:user",
          }
        - {
            regexp: "^file-db:/usr/share/gdm/greeter-dconf-defaults",
            line: "file-db:/usr/share/gdm/greeter-dconf-defaults",
            insertafter: "system-db:{{ cis_dconf_db_name }}",
          }
  notify: Update dconf
  when:
    - cis_desktop_required
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.7.3
    - gnome

- name: "1.7.4 | Ensure GDM screen locks when the user is idle"
  block:
    - name: "1.7.4 | Ensure GDM screen locks when the user is idle | Session profile"
      lineinfile:
        path: "/etc/dconf/profile/{{ cis_dconf_db_name }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.after | default(omit) }}"
        create: true
      loop:
        - { regexp: "user-db:user", line: "user-db:user" }
        - {
            regexp: "system-db:{{ cis_dconf_db_name }}",
            line: "system-db:{{ cis_dconf_db_name }}",
            after: "^user-db.*",
          }

    - name: "1.7.4 | Ensure GDM screen locks when the user is idle | Make directory"
      file:
        path: "/etc/dconf/db/{{ cis_dconf_db_name }}.d"
        owner: root
        group: root
        mode: "0755"
        state: directory
      notify: Update dconf

    - name: "1.7.4 | Ensure GDM screen locks when the user is idle | Session script"
      template:
        src: etc/dconf/db/00-screensaver.j2
        dest: "/etc/dconf/db/{{ cis_dconf_db_name }}.d/00-screensaver"
        owner: root
        group: root
        mode: "0644"
      notify: Update dconf
  when:
    - cis_desktop_required
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.7.4
    - gnome

- name: "1.7.5 | Ensure GDM screen locks cannot be overridden"
  block:
    - name: "1.7.5 | Ensure GDM screen locks cannot be overridden | Make lock directory"
      file:
        path: "/etc/dconf/db/{{ cis_dconf_db_name }}.d/locks"
        owner: root
        group: root
        mode: "0755"
        state: directory
      notify: Update dconf

    - name: "1.7.5 | Ensure GDM screen locks cannot be overridden | Make lockfile"
      template:
        src: etc/dconf/db/00-screensaver_lock.j2
        dest: "/etc/dconf/db/{{ cis_dconf_db_name }}.d/locks/00-screensaver"
        owner: root
        group: root
        mode: "0644"
      notify: Update dconf
  when:
    - cis_desktop_required
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.7.5
    - gnome

- name: "1.7.6 | Ensure GDM automatic mounting of removable media is disabled"
  block:
    - name: "1.7.6 | Ensure GDM automatic mounting of removable media is disabled | Make directory"
      file:
        path: "/etc/dconf/db/{{ cis_dconf_db_name }}.d"
        owner: root
        group: root
        mode: "0755"
        state: directory
      notify: Update dconf

    - name: "1.7.6 | Ensure GDM automatic mounting of removable media is disabled | Session script"
      template:
        src: etc/dconf/db/00-media-automount.j2
        dest: "/etc/dconf/db/{{ cis_dconf_db_name }}.d/00-media-automount"
        owner: root
        group: root
        mode: "0644"
      notify: Update dconf
  when:
    - cis_desktop_required
  tags:
    - level1-server
    - level2-workstation
    - automated
    - patch
    - 1.7.6
    - gnome

- name: "1.7.7 | Ensure GDM disabling automatic mounting of removable media is not overridden"
  block:
    - name: "1.7.7 | Ensure GDM disabling automatic mounting of removable media is not overridden | Make lock directory"
      file:
        path: "/etc/dconf/db/{{ cis_dconf_db_name }}.d/locks"
        owner: root
        group: root
        mode: "0755"
        state: directory
      notify: Update dconf

    - name: "1.7.7 | Ensure GDM disabling automatic mounting of removable media is not overridden | Make lockfile"
      template:
        src: etc/dconf/db/00-automount_lock.j2
        dest: "/etc/dconf/db/{{ cis_dconf_db_name }}.d/locks/00-automount_lock"
        owner: root
        group: root
        mode: "0644"
      notify: Update dconf
  when:
    - cis_desktop_required
  tags:
    - level1-server
    - level2-workstation
    - automated
    - patch
    - 1.7.7
    - gnome

- name: "1.7.8 | Ensure GDM autorun-never is enabled"
  block:
    - name: "1.7.8 | Ensure GDM autorun-never is enabled | Make directory"
      file:
        path: "/etc/dconf/db/{{ cis_dconf_db_name }}.d"
        owner: root
        group: root
        mode: "0755"
        state: directory
      notify: Update dconf

    - name: "1.7.8 | Ensure GDM autorun-never is enabled | Session script"
      template:
        src: etc/dconf/db/00-media-autorun.j2
        dest: "/etc/dconf/db/{{ cis_dconf_db_name }}.d/00-media-autorun"
        owner: root
        group: root
        mode: "0644"
      notify: Update dconf
  when:
    - cis_desktop_required
  tags:
    - level1-server
    - level2-workstation
    - automated
    - patch
    - 1.7.8
    - gnome

- name: "1.7.9 | Ensure GDM autorun-never is not overridden"
  block:
    - name: "1.7.9 | Ensure GDM autorun-never is not overridden | make lock directory"
      file:
        path: "/etc/dconf/db/{{ cis_dconf_db_name }}.d/locks"
        owner: root
        group: root
        mode: "0755"
        state: directory
      notify: Update dconf

    - name: "1.7.9 | Ensure GDM autorun-never is not overridden | make lockfile"
      template:
        src: etc/dconf/db/00-autorun_lock.j2
        dest: "/etc/dconf/db/{{ cis_dconf_db_name }}.d/locks/00-autorun_lock"
        owner: root
        group: root
        mode: "0644"
      notify: Update dconf
  when:
    - cis_desktop_required
  tags:
    - level1-server
    - level2-workstation
    - automated
    - patch
    - 1.7.9
    - gnome

- name: "1.7.10 | Ensure XDCMP is not enabled"
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: "^Enable.*=.*true"
    state: absent
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.7.10
    - gnome
    - xdcmp
