---
- name: "1.1.2.1 | Configure /tmp"
  block:
    - name: "1.1.2.1.1 | Ensure /tmp is a separate partition"
      block:
        - name: "1.1.2.1.1 | Ensure /tmp is a separate partition | Absent"
          debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

        - name: "1.1.2.1.1 | Ensure /tmp is a separate partition | warn_count"
          import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: "1.1.2.1.1"
      when:
        - required_mount not in mount_names
      tags:
        - level1-server
        - level1-workstation
        - audit
        - mounts
        - 1.1.2.1.1
        - tmp

    - name: "1.1.2.1.2 | Ensure nodev option set on /tmp partition"
      set_fact:
        tmp_partition_mount_options: "{{ tmp_partition_mount_options + [ 'nodev' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.1.2
        - tmp

    - name: "1.1.2.1.3 | Ensure nosuid option set on /tmp partition"
      set_fact:
        tmp_partition_mount_options: "{{ tmp_partition_mount_options + [ 'nosuid' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.1.3
        - tmp

    - name: "1.1.2.1.4 | Ensure noexec option set on /tmp partition"
      set_fact:
        tmp_partition_mount_options: "{{ tmp_partition_mount_options + [ 'noexec' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.1.4
        - tmp
  vars:
    required_mount: "/tmp"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.1.2.1
    - tmp

- name: "1.1.2.2 | Configure /dev/shm"
  block:
    - name: "1.1.2.2.1 | Ensure /dev/shm is a separate partition"
      block:
        - name: "1.1.2.2.1 | Ensure /dev/shm is a separate partition | Absent"
          debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

        - name: "1.1.2.2.1 | Ensure /dev/shm is a separate partition | warn_count"
          import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: "1.1.2.2.1"
      when:
        - required_mount not in mount_names
      tags:
        - level1-server
        - level1-workstation
        - audit
        - mounts
        - 1.1.2.2.1
        - tmp

    - name: "1.1.2.2.2 | Ensure nodev option set on /dev/shm partition"
      set_fact:
        dev_shm_partition_mount_options: "{{ dev_shm_partition_mount_options + [ 'nodev' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.2.2
        - tmp

    - name: "1.1.2.2.3 | Ensure nosuid option set on /dev/shm partition"
      set_fact:
        dev_shm_partition_mount_options: "{{ dev_shm_partition_mount_options + [ 'nosuid' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.2.3
        - tmp

    - name: "1.1.2.2.4 | Ensure noexec option set on /dev/shm partition"
      set_fact:
        dev_shm_partition_mount_options: "{{ dev_shm_partition_mount_options + [ 'noexec' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.2.4
        - tmp
  vars:
    required_mount: "/dev/shm"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.1.2.2
    - tmp

- name: "1.1.2.3 | Configure /home"
  block:
    - name: "1.1.2.3.1 | Ensure /home is a separate partition"
      block:
        - name: "1.1.2.3.1 | Ensure /home is a separate partition | Absent"
          debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

        - name: "1.1.2.3.1 | Ensure /home is a separate partition | warn_count"
          import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: "1.1.2.3.1"
      when:
        - required_mount not in mount_names
      tags:
        - level1-server
        - level1-workstation
        - audit
        - mounts
        - 1.1.2.3.1
        - tmp

    - name: "1.1.2.3.2 | Ensure nodev option set on /home partition"
      set_fact:
        home_partition_mount_options: "{{ home_partition_mount_options + [ 'nodev' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.3.2
        - tmp

    - name: "1.1.2.3.3 | Ensure nosuid option set on /home partition"
      set_fact:
        home_partition_mount_options: "{{ home_partition_mount_options + [ 'nosuid' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.3.3
        - tmp

    - name: "1.1.2.3.4 | Ensure noexec option set on /home partition"
      set_fact:
        home_partition_mount_options: "{{ home_partition_mount_options + [ 'noexec' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.3.4
        - tmp
  vars:
    required_mount: "/home"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.1.2.3
    - tmp

- name: "1.1.2.4 | Configure /var"
  block:
    - name: "1.1.2.4.1 | Ensure /var is a separate partition"
      block:
        - name: "1.1.2.4.1 | Ensure /var is a separate partition | Absent"
          debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

        - name: "1.1.2.4.1 | Ensure /var is a separate partition | warn_count"
          import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: "1.1.2.4.1"
      when:
        - required_mount not in mount_names
      tags:
        - level1-server
        - level1-workstation
        - audit
        - mounts
        - 1.1.2.4.1
        - tmp

    - name: "1.1.2.4.2 | Ensure nodev option set on /var partition"
      set_fact:
        var_partition_mount_options: "{{ var_partition_mount_options + [ 'nodev' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.4.2
        - tmp

    - name: "1.1.2.4.3 | Ensure nosuid option set on /var partition"
      set_fact:
        var_partition_mount_options: "{{ var_partition_mount_options + [ 'nosuid' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.4.3
        - tmp

    - name: "1.1.2.4.4 | Ensure noexec option set on /var partition"
      set_fact:
        var_partition_mount_options: "{{ var_partition_mount_options + [ 'noexec' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.4.4
        - tmp
  vars:
    required_mount: "/var"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.1.2.4
    - tmp

- name: "1.1.2.5 | Configure /var/tmp"
  block:
    - name: "1.1.2.5.1 | Ensure /var/tmp is a separate partition"
      block:
        - name: "1.1.2.5.1 | Ensure /var/tmp is a separate partition | Absent"
          debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

        - name: "1.1.2.5.1 | Ensure /var/tmp is a separate partition | warn_count"
          import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: "1.1.2.5.1"
      when:
        - required_mount not in mount_names
      tags:
        - level1-server
        - level1-workstation
        - audit
        - mounts
        - 1.1.2.5.1
        - tmp

    - name: "1.1.2.5.2 | Ensure nodev option set on /var/tmp partition"
      set_fact:
        var_tmp_partition_mount_options: "{{ var_tmp_partition_mount_options + [ 'nodev' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.5.2
        - tmp

    - name: "1.1.2.5.3 | Ensure nosuid option set on /var/tmp partition"
      set_fact:
        var_tmp_partition_mount_options: "{{ var_tmp_partition_mount_options + [ 'nosuid' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.5.3
        - tmp

    - name: "1.1.2.5.4 | Ensure noexec option set on /var/tmp partition"
      set_fact:
        var_tmp_partition_mount_options: "{{ var_tmp_partition_mount_options + [ 'noexec' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.5.4
        - tmp
  vars:
    required_mount: "/var/tmp"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.1.2.5
    - tmp

- name: "1.1.2.6 | Configure /var/log"
  block:
    - name: "1.1.2.6.1 | Ensure /var/log is a separate partition"
      block:
        - name: "1.1.2.6.1 | Ensure /var/log is a separate partition | Absent"
          debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

        - name: "1.1.2.6.1 | Ensure /var/log is a separate partition | warn_count"
          import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: "1.1.2.6.1"
      when:
        - required_mount not in mount_names
      tags:
        - level1-server
        - level1-workstation
        - audit
        - mounts
        - 1.1.2.6.1
        - tmp

    - name: "1.1.2.6.2 | Ensure nodev option set on /var/log partition"
      set_fact:
        var_log_partition_mount_options: "{{ var_log_partition_mount_options + [ 'nodev' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.6.2
        - tmp

    - name: "1.1.2.6.3 | Ensure nosuid option set on /var/log partition"
      set_fact:
        var_log_partition_mount_options: "{{ var_log_partition_mount_options + [ 'nosuid' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.6.3
        - tmp

    - name: "1.1.2.6.4 | Ensure noexec option set on /var/log partition"
      set_fact:
        var_log_partition_mount_options: "{{ var_log_partition_mount_options + [ 'noexec' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.6.4
        - tmp
  vars:
    required_mount: "/var/log"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.1.2.6
    - tmp

- name: "1.1.2.7 | Configure /var/log/audit"
  block:
    - name: "1.1.2.7.1 | Ensure /var/log/audit is a separate partition"
      block:
        - name: "1.1.2.7.1 | Ensure /var/log/audit is a separate partition | Absent"
          debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

        - name: "1.1.2.7.1 | Ensure /var/log/audit is a separate partition | warn_count"
          import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: "1.1.2.7.1"
      when:
        - required_mount not in mount_names
      tags:
        - level1-server
        - level1-workstation
        - audit
        - mounts
        - 1.1.2.7.1
        - tmp

    - name: "1.1.2.7.2 | Ensure nodev option set on /var/log/audit partition"
      set_fact:
        var_log_audit_partition_mount_options: "{{ var_log_audit_partition_mount_options + [ 'nodev' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.7.2
        - tmp

    - name: "1.1.2.7.3 | Ensure nosuid option set on /var/log/audit partition"
      set_fact:
        var_log_audit_partition_mount_options: "{{ var_log_audit_partition_mount_options + [ 'nosuid' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.7.3
        - tmp

    - name: "1.1.2.7.4 | Ensure noexec option set on /var/log/audit partition"
      set_fact:
        var_log_audit_partition_mount_options: "{{ var_log_audit_partition_mount_options + [ 'noexec' ] }}"
      changed_when: true
      notify: Writing and remounting tmp
      when:
        - required_mount in mount_names
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - 1.1.2.7.4
        - tmp
  vars:
    required_mount: "/var/log/audit"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - 1.1.2.7
    - tmp
